Rhel 8 update
redhat-plumbers/dracut-rhel8 pull request #18
Opened 2022-08-11 12:18 UTC by pvalena

WIP

2022-08-13 23:38 UTC, pvalena commented on modules.d/80lvmthinpool-monitor/start-thinpool-monitor.sh
> +type getarg > /dev/null 2>&1 || . /lib/dracut-lib.sh
@jamacku this is not helpful, as it means it will not know the variables / methods, that are used all over dracut modules.

2022-08-14 05:53 UTC, jamacku commented on modules.d/80lvmthinpool-monitor/start-thinpool-monitor.sh
> +type getarg > /dev/null 2>&1 || . /lib/dracut-lib.sh
@pvalena I'll have a look, it should be easy to fix. Thanks for info.

2022-08-14 06:39 UTC, jamacku commented on modules.d/80lvmthinpool-monitor/start-thinpool-monitor.sh
> +type getarg > /dev/null 2>&1 || . /lib/dracut-lib.sh
In upstream, they strait up disabled these checks - https://github.com/dracutdevs/dracut/blob/2334031a890a1101c78f986681236c76ba806d91/.shellcheckrc

But I think it is not the best solution. ShellCheck can source external files before linting. I'll try that and get back to you.

2022-08-15 07:43 UTC, jamacku commented on modules.d/80lvmthinpool-monitor/start-thinpool-monitor.sh
> +type getarg > /dev/null 2>&1 || . /lib/dracut-lib.sh
@pvalena Looks like the best way how to deal with is kind of error is to backport `.shellcheckrc` from upstream. There is also an option to declare those external variables at the top of the script (non-POSIX):

```shell
declare moddir initdir systemdsystemunitdir
```

There are some related issues on ShellCheck upstream:
- https://github.com/koalaman/shellcheck/issues/356
- https://github.com/koalaman/shellcheck/issues/2356

2022-08-15 07:50 UTC, jamacku requested changes
Commits messages are missing `(cherry picked from commit <XYZ>)` note.

2022-08-15 07:58 UTC, pvalena commented
> Commit messages are missing `(cherry picked from commit <XYZ>)` note.

Well, no sure how that'd help much- they're the identical upstream commits as in the PRs (which are linked in the BZ).

2022-08-15 07:59 UTC, pvalena commented
> > Commit messages are missing `(cherry picked from commit <XYZ>)` note.
> 
> Well, no sure how that'd help much- they're the identical upstream commits as in the PRs (which are linked in the BZ).

_Note: we've never linked commits AFAIR_

2022-08-15 08:02 UTC, jamacku commented
> _Note: we've never linked commits AFAIR_

Sure, I just noted, that the last commit on main has an upstream patch linked, so I thought you have forgot.

2022-08-15 08:31 UTC, pvalena commented
> Sure, I just noted, that the last commit on main has an upstream patch linked, so I thought you have forgot.

Oh you're right, the bot did that. I've never noticed :). Thanks for checking!

2022-08-15 08:37 UTC, pvalena commented on modules.d/80lvmthinpool-monitor/start-thinpool-monitor.sh
> +type getarg > /dev/null 2>&1 || . /lib/dracut-lib.sh
> .shellcheckrc

There's no such file in upstream.

2022-08-15 08:41 UTC, jamacku commented on modules.d/80lvmthinpool-monitor/start-thinpool-monitor.sh
> +type getarg > /dev/null 2>&1 || . /lib/dracut-lib.sh
here: https://github.com/dracutdevs/dracut/blob/master/.shellcheckrc

2022-08-15 08:43 UTC, pvalena commented on modules.d/80lvmthinpool-monitor/start-thinpool-monitor.sh
> +type getarg > /dev/null 2>&1 || . /lib/dracut-lib.sh
EDIT: I'm not sure why it didn't want to check out earlier... I'll sync the file from upstream, thanks!

2022-08-15 08:46 UTC, pvalena commented on modules.d/80lvmthinpool-monitor/start-thinpool-monitor.sh
> +type getarg > /dev/null 2>&1 || . /lib/dracut-lib.sh
Not sure what did happen earlier,

I run ` find -type f -name .shellcheckrc ` and got 0 results on `origin/master`....

2022-08-15 09:27 UTC, pvalena commented
Scratch build tier1 tests: `Finished: SUCCESS`. Let's move this forward.

2022-08-15 09:27 UTC, merged